# Generated by Django 2.0 on 2021-06-22 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='sellar',
            new_name='seller',
        ),
    ]
